version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: simple_orders_development
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"

volumes:
  pgdata: